spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      groupId: 12345
      auto-offset-reset: latest
      enable-auto-commit: false
    producer:
      bootstrap-servers: localhost:9092

