# Default values for kafka-consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
configmap: |-

  app:
    delay: 30
  spring:
    jmx:
      enabled: true
    config:
      activate:
        on-profile: kubernetes
    kafka:
      listener:
        concurrency: 5
      consumer:
        bootstrap-servers: kafka-boostrap-2436716-sng01.clb.appdomain.cloud:9093
        topics: perf-1
        client-id: '${pod.name}_${pod.namespace}_${pod.id}'
        properties:
          enable.auto.commit: true
          fetch.min.bytes: 100000
          fetch.max.wait.ms: 500
          max.poll.records: 500
          max.partition.fetch.bytes: 50000000
      producer:
        acks: all
        bootstrap-servers: kafka-boostrap-2436716-sng01.clb.appdomain.cloud:9093
        topic: perf-1
        client-id: '${pod.name}_${pod.namespace}_${pod.id}'
        properties:
          acks: 1
          linger.ms: 10
          batch.size: 100000
          buffer.memory: 93554432
  management:
    endpoint:
      health:
        show-details: ALWAYS
      restart:
        enabled: true
    endpoints:
      web:
        exposure:
          include: 'health,info,prometheus,metrics,env'



replicaCount: 10

image:
  repository: quay.io/linxianer12/kafka-consumer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.28

imagePullSecrets:
  - name: quay
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    route.openshift.io/termination: "edge"
  hosts:
    - host: kafka-consumer-1.th-client-engineering-f6b6402521be9cea8454becf471bf859-0000.sng01.containers.appdomain.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources:
  limits:
    cpu: 2
    memory: 1.5Gi
  requests:
    cpu: 300m
    memory: 768Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
