apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-consumer.fullname" . }}
  labels:
  {{- include "kafka-consumer.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- if .Values.configmap }}
    {{- .Values.configmap | nindent 4 }}
  {{- end }}